-- Create approval_codes table for school-based family approval system
-- Each code is a 3-letter school prefix + 6-digit number (e.g., RBE123456)
-- Codes are pre-generated by admins and distributed to schools at the start of each year

CREATE TABLE IF NOT EXISTS approval_codes (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    code VARCHAR(9) NOT NULL UNIQUE, -- Format: ABC123456 (3 letters + 6 digits)
    school_code VARCHAR(3) NOT NULL, -- 3-letter school prefix (e.g., RBE, NEA, AOA)
    community_id BIGINT NOT NULL, -- References the community/school this code belongs to
    is_claimed BOOLEAN DEFAULT false, -- Whether the code has been used
    claimed_by UUID REFERENCES auth.users (id), -- User who claimed this code
    claimed_at TIMESTAMPTZ, -- When the code was claimed
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users (id) -- Admin who generated the codes
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_approval_codes_code ON approval_codes (code);

CREATE INDEX IF NOT EXISTS idx_approval_codes_community ON approval_codes (community_id);

CREATE INDEX IF NOT EXISTS idx_approval_codes_school_code ON approval_codes (school_code);

CREATE INDEX IF NOT EXISTS idx_approval_codes_unclaimed ON approval_codes (is_claimed)
WHERE
    is_claimed = false;

CREATE INDEX IF NOT EXISTS idx_approval_codes_claimed_by ON approval_codes (claimed_by);

-- Add community_id column to users table (links user to their school/community)
ALTER TABLE users ADD COLUMN IF NOT EXISTS community_id BIGINT;

-- Comments
COMMENT ON
TABLE approval_codes IS 'Pre-generated approval codes distributed to schools. Each code links a family to a specific community/school.';

COMMENT ON COLUMN approval_codes.code IS 'Full approval code: 3-letter school prefix + 6-digit number (e.g., RBE123456)';

COMMENT ON COLUMN approval_codes.school_code IS '3-letter uppercase prefix identifying the school (e.g., RBE for Ruby Bridges Elementary)';

COMMENT ON COLUMN approval_codes.community_id IS 'The community/school this code belongs to';

COMMENT ON COLUMN approval_codes.is_claimed IS 'Whether this code has been used by a family during signup';

COMMENT ON COLUMN users.community_id IS 'The community/school the user belongs to, set automatically from their approval code during signup';